name: mental_app
description: A new Flutter project
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.5.0 <4.0.0"   # compatible with Flutter 3.35 (Dart 3.5.x)

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  shared_preferences: ^2.5.3
  fl_chart: ^1.1.1
  firebase_core: ^4.2.1
  cloud_firestore: ^6.1.0
  youtube_player_flutter: ^8.1.2
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
     uses-material-design: true
     
     assets:
       - lib/assets/images/Innerbloom.png

dependencies:
  http: ^1.2.0
       